chore: added package publishing steps to release workflow
justtrackio/ssm-diff pull request #4
Opened 2024-08-13 08:29 UTC by pehlicd

## Description

## Motivation and Context

## Breaking Changes

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-08-13 09:12 UTC, applike-ss requested changes

2024-08-13 09:12 UTC, applike-ss commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
will this be added again based on our template in our github management repo?

2024-08-13 09:12 UTC, applike-ss commented on .github/workflows/release.yml
> +        uses: docker/setup-buildx-action@v3
based on this, it looks like you don't need this? https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

2024-08-13 09:12 UTC, applike-ss commented on Dockerfile
> +FROM public.ecr.aws/docker/library/alpine:3.20
Can we use distroless here?

2024-08-13 09:29 UTC, pehlicd commented on .github/workflows/release.yml
> +        uses: docker/setup-buildx-action@v3
actually it is needed for building multi-arch image

2024-08-13 09:30 UTC, pehlicd commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
I don't think so since we will probably not have any examples for this repository

2024-08-13 10:04 UTC, applike-ss commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
I know, that was also not my question. The file is managed however in out github management repository, isn't it? So the next apply will wipe out these changes, unless you blacklist it for this repo somehow.

2024-08-13 10:04 UTC, applike-ss commented on .github/workflows/release.yml
> +        uses: docker/setup-buildx-action@v3
ahh isee

2024-08-14 13:38 UTC, applike-ss approved these changes

2024-08-14 13:39 UTC, merged